# Use the official Node.js 18 base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install dependenciezs
RUN npm install

# Copy the entire project into the container
COPY . .

# Compile TypeScript to JavaScript
RUN npx tsc

# Expose the application port (adjust if needed)
EXPOSE 3000

# Set the command to start the application
CMD ["node", "dist/app.js"]
